
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/components/appContext";


const inter = Inter({
  variable: "--font-inter", // optional
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins", // optional
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} antialiased`} >
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}